### PR TITLE
Menu adjacent slot

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**
Here's a screencast of the demo:
menu adjacent

### CODE REVIEW

**Comment by jstefaniuk-d2l** [comment]
Ready for review I'd say, I left any animating up to the consumer, but added @trevorjonesd2l animation into the course-tile-esque demo

**Comment by ryantmer** [comment]
So is the idea here to have the extra menu item only show on click?

**Comment by jstefaniuk-d2l** [comment]
The demo toggles on click just because it was the easiest way to demo that the animation was possible

**Comment by jstefaniuk-d2l** [comment]
All this really is is a slot that goes beside the `...` menu

**Pull request merged**
