### PR TITLE
Inline demo

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**
Looks good, but it takes a couple minutes to load the inline demo when previewing, how long is too long?

fixes: https://github.com/BrightspaceUI/tile/issues/25

### CODE REVIEW

**Comment by dlockhart** [comment]
Haha, a couple minutes sounds too long I think?

**Comment by jstefaniuk-d2l** [comment]
Just had someone else hit the link and it looks like the slowness may just be on initial load:
https://www.webcomponents.org/preview/jstefaniuk-d2l/tile/3ff3fd4177c34456e628bca28b4ca5ca840c3e30

**Comment by dbatiste** [comment]
Yeah, on the first time it does a bunch of stuff.  Code mirroring and caching I think.  Once it's done that work, it loads fine from my experience.

**Comment by dbatiste** [comment]
For the [button-group demo](https://www.webcomponents.org/preview/BrightspaceUI/button-group/d0c7bf2b3fe3e165c171921348e44ce7ecb0f437), I decided to forego the screenshot since on webcomponents.org it becomes pretty redundant and it's not as crisp.  My goal was to keep the doc clear and concise, with the demo close to the top if possible.  The downside is ditching the screenshot is that there is no visual when viewing the readme on GitHub.  Not sure what you guys think...?  I am hoping to go through our shared repos this week to make updates.

**Comment by ryantmer** [comment]
Personal opinion is that the screenshots are nice, even if they're not great quality - although I guess the demo can run on webcomponents.org anyway, which is probably a better way to get an idea of what the component looks like/does.

So... I just went full circle in one sentence I guess 😛

**Comment by dbatiste** [comment]
The other thing I like about the live demo over the screenshot is that it will automatically reflect non-breaking changes.  Obviously, if changes to the API are made, changes to the demo code sample may be necessary.  The screenshots get out of date easily.

**Comment by dlockhart** [comment]
I'm also not totally against screenshots, especially of the animated GIF variety (Giphy Capture app rocks). Outside of webcomponents.org, I find they can provide a really quick overview of what the component does in its most basic form.

You're all very correct though in that they can fall out of date quickly, especially for components which haven't stabilized yet.

**Comment by dbatiste** [comment]
It would be nice if we could show the screenshot on GitHub but not on webcomponents.org, where we show the live demo.

**Comment by jstefaniuk-d2l** [comment]
I also kind of like the screenshots because many people probably won't know to click on webcomponents.org for a live demo

**Pull request merged**
